package com.belajar.pekanbaruapps.navigation

sealed class AppRoute(val route:String) {
    object Onboarding:AppRoute("onboarding")
    object Profile:AppRoute("profile")
    object EditProfile:AppRoute("editprofile")
    object Login:AppRoute("login")
    object Signup:AppRoute("signup")
    object Home:AppRoute("home")
    object HotelPekanbaru:AppRoute("hotelpekanbaru")
    object DetailHotel:AppRoute("detailhotel")
    object Restaurant:AppRoute("restaurant")
    object DetailRestaurant:AppRoute("detailrestaurant")
    object Wisata:AppRoute("wisata")
    object WisataDetail:AppRoute("wisatadetail")
    object Pembelanjaan:AppRoute("pembelanjaan")
    object BelanjaDetail:AppRoute("belanjadetail")
    object Pendidikan:AppRoute("pendidikan")
    object SMPDetail:AppRoute("smpdetail")
    object SDDetail:AppRoute("sddetail")
    object Kesehatan:AppRoute("kesehatan")
    object KesehatanDetail:AppRoute("kesehatanDetail")
    object Berita:AppRoute("berita")
    object DetailBerita:AppRoute("detailberita")
    object Magazine:AppRoute("magazine")
    object Pengumuman:AppRoute("pengumuman")
    object PengumumanDetail:AppRoute("pengumumandetail")
    object Galeri:AppRoute("galeri")
    object DetailGaleri:AppRoute("detailgaleri")
}
